services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  portfolio-site:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
    restart: unless-stopped

  management-ui:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/var/data
    restart: unless-stopped

  jellyfin:           # <--- Make sure this is indented 2 spaces!
      image: jellyfin/jellyfin
      container_name: jellyfin
      network_mode: bridge
      ports:
        - 8096:8096
      volumes:
        - ./jellyfin-config:/config
        - ./media/movies:/data/movies
        - ./media/music:/data/music
      restart: unless-stopped


volumes:
  portainer_data:

