- My Lab:
    - Portfolio:
        icon: nginx.png
        href: http://localhost:8080
        server: my-docker
        container: my-portfolio-portfolio-site-1
        showStats: true

    - Portainer:
        icon: portainer.png
        href: http://localhost:9000
        server: my-docker
        container: my-portfolio-management-ui-1
        showStats: true
