- My Lab:
    - Portfolio:
        icon: nginx.png
        href: http://localhost:8080
        description: "(IP: 10.0.2.15:8080)"
        server: my-docker
        container: my-portfolio-portfolio-site-1
        showStats: true

    - Portainer:
        icon: portainer.png
        href: http://localhost:9000
        description: "(IP: 10.0.2.15:9000)"
        server: my-docker
        container: my-portfolio-management-ui-1
        showStats: true

- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://100.94.75.59:8096
        description: "Private Media Server (IP: 10.0.2.15:8096)"
        server: my-docker
        container: jellyfin
        showStats: true
        widget:
          type: jellyfin
          url: http://jellyfin:8096
          key: 42c27e7bee654a749c0a24dfd312bb47

- Entertainment:
    - Kavita:
        icon: kavita.png
        href: http://10.0.2.15:5000
        description: "Digital Manga & Books (10.0.2.15:5000)"
        widget:
          type: kavita
          url: http://kavita:5000

- Infrastructure:
    - Tailscale:
        icon: tailscale.png
        href: https://login.tailscale.com/admin/machines
        description: Secure Mesh Network
        widget:
        type: tailscale
        deviceid: kfjWDefWC221CNTRL
        key: tskey-api-kfjWDefWC221CNTRL-qTgviEqA7hfCZVQ6UWargfW5kEAALhZDP
