---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- greeting:
    text_size: l
    text: "Welcome to the Lab!"

- datetime:
    format:
      timeStyle: short
      hourCycle: h23

- search:
    provider: google
    target: _blank

- resources:
    cpu: true
    memory: true
    disk: /
